### PR TITLE
Freezed

### PR DESCRIPTION
**Pull request by sam-parks**

### CODE REVIEW

**Comment by SimonIT** [comment]
Can you convert this PR to a draft until you are ready with your work?

**Comment by SimonIT** [comment]
Hey guys, what's the state of this PR? I want to publish this lib with null safety. To avoid any conflicts with this PR I'm waiting on you. If you are finished with the changes, I would begin with reviewing it

**Comment by blackbeario** [comment]
Hello @sam-parks, I pulled down your branch Clean-Simple-Eats:freezed to see if I could get it running locally, which I did. I am hoping to contribute to this code with my own PR since it's been quite a while since your submission. Question, did you need to add your Shopify store _password_ in the configuration anywhere? I am asking because when I run the example project with the example API key (**yes your API key is in the PR in the example**), the products load fine. But when I use _my_ test store API key and try to load my products into the app, I get this error:

flutter: OperationException(linkException: ResponseFormatException(originalException: FormatException: Unexpected end of input (at character 1) 

So either there's some issue with my Shopify test store, or I've failed to configure something in this example. Since I didn't add my store password anywhere, I was wondering if that might be the problem. Thanks!

**Comment by no-1ne** [comment]
Any love for this. Seems like null safety is also coming via this

**Comment by SimonIT** [comment]
Hey guys, I fixed some some things for my app in the [freezed](https://github.com/ThinkSimple/flutter_simple_shopify/tree/freezed) branch. If you're fine with the changes I'll merge them on master on the weekend. @sam-parks @mrgnhnt96 @no-1ne @purushothrps @sezrab

**Pull request closed without merging**
