### PR TITLE
Add SelectedOptions to ProductVariants

### PR DESCRIPTION
**Pull request by tuarrep**

### CODE REVIEW

**Comment by ThinkSimple** [comment]
Hey, there are plenty queries that return product variants, I dont know exactly how many there are but can you check the queries that return ProductVariants and add the selectedOptions to each and every one?

**Comment by tuarrep** [comment]
@ThinkSimple 

Sorry for the delay, it's done

**Comment by SimonIT** [comment]
@tuarrep Do you mind fixing the conflicts?

**Comment by SimonIT** [comment]
Rebased it and pushed in directly (5fe432db6877b024521b9b1d542fc13a78533691 & 8f4b2d0ab53de722c751601133bef20d539c722f)

**Pull request closed without merging**
