### PR TITLE
Upgrade graphql

### LINKED ISSUE #64: Using old dependencies
The majority of the flutter pub packages upgraded to use the new null safety features of Flutter 2.0, so if we wan to switch to Flutter 2.0, we need support from the majority of the packages.

This library relies on graphql ^3.1.0 but firebase_auth >=1.0.0 relies on http_parser ^4.0.0 which makes it impossible to upgrade without upgrading this libraby.

Can we upgrade this library as well to use flutter 2.0 and the latest pub packages?

### PR DESCRIPTION
**Pull request by SimonIT**
I'm not totally sure, if `deleteThisPartOfCache` still works. Feel free to try it
It adds also the nice possibility to set how to cache
closes #64

### CODE REVIEW

**Review by jupanubv92 — APPROVED** [review]

**Comment by SimonIT** [comment]
There is a problem with `getAllProductsFromCollectionById` (and maybe other methods):
`NoSuchMethodError: Class '_InternalLinkedHashMap<String, dynamic>' has no instance getter 'data'.`
That's why I didn't have merged it.
If someone has an idea how to work around it, please tell me

**Comment by SimonIT** [comment]
Okay, I found the problem and fixed it. 
I think it's ready to merge. 

I will wait some days so you guys can try it.
I would really appreciate if you do
@jupanubv92 @tuarrep @zeshuaro @mostafaAbdelazim @newdeveloper15 @emvaized @KieranLafferty
(Sorry for the mentions)

This is how you can test the changes. Just put this snippet inside your pubspec.yml:
```
  flutter_simple_shopify:
    git:
       url: https://github.com/SimonIT/flutter_simple_shopify.git
       ref: graphql-upgrade
```

**Comment by mostafaAbdelazim** [comment]
Thanks @SimonIT for the fix, I will give it a try on Sunday

**Comment by mostafaAbdelazim** [comment]
@SimonIT 
Looks good, I've been able to authenticate and edit user object, Good job man, thanks for your time

**Comment by mostafaAbdelazim** [comment]
@SimonIT 
Hi Simon, I'm further testing the latest version, when i'm calling the ShopifyStore.instance.getAllProducts method, i'm getting an OperationException, not sure if this is related to this pr or not

**Comment by SimonIT** [comment]
Can you post the full stack trace?

**Comment by mostafaAbdelazim** [comment]
@SimonIT 
Stacktrace:
ShopifyError.checkForError (package:flutter_simple_shopify/mixins/src/shopfiy_error.dart:8:7)
     ShopifyStore.getAllProducts (package:flutter_simple_shopify/shopify/src/shopify_store.dart:48:7)
<asynchronous suspension>
      ShopifyHelper.getAllProducts (package:shopertino/services/ShopifyHelper.dart:93:27)
<asynchronous suspension>
      BackendManager.getProducts (package:shopertino/services/BackendManager.dart:181:16)
<asynchronous suspension>
      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart)
<asynchronous suspension>

Full exception log:
 OperationException(linkException: UnexpectedResponseStructureException(PartialDataException(path: products.edges.node.metafields), request: Request(operation: Operation(document: DocumentNode("query($cursor: String, $shouldFetchMetafields: Boolean = false, $metafieldsNamespace: String) {\n  __typename\n  products(first: 250, after: $cursor) {\n    __typename\n    pageInfo {\n      __typename\n      hasNextPage\n    }\n    edges {\n      __typename\n      cursor\n      node {\n        __typename\n        options(first: 50) {\n          __typename\n          id\n          name\n          values\n        }\n        metafields(namespace: $metafieldsNamespace, first: 250) @include(if: $shouldFetchMetafields) {\n          __typename\n          edges {\n            __typename\n            node {\n              __typename\n              id\n              namespace\n              key\n              value\n              valueType\n              description\n         <…>

**Comment by SimonIT** [comment]
Do you know whether it work with master?
```
  flutter_simple_shopify:
    git:
       url: https://github.com/ThinkSimple/flutter_simple_shopify.git
       ref: master
```
I don't think that it's related to this PR, but then we are sure.
We have to fix it anyway if it's related or not

**Comment by mostafaAbdelazim** [comment]
Yes, it works fine on master

**Comment by tuarrep** [comment]
Not tested extensively but lgtm

**Comment by SimonIT** [comment]
> Yes, it works fine on master

Then I will investigate further more

**Comment by SimonIT** [comment]
I found the change in their changelog:

> client: cache writes are now strict, and throw PartialDataException (from normalize), ([616b5ed](https://github.com/zino-app/graphql-flutter/commit/616b5edb503ce68d0212c5da8a9df69a9df30782))

This in combination with this conditional include let it blow up:
https://github.com/ThinkSimple/flutter_simple_shopify/blob/dcf723aca31401182faa621c396f2906c777fc4e/lib/graphql_operations/queries/get_products.dart#L15

I'm happy, that we found this problem before merging.

**Comment by SimonIT** [comment]
Thanks guys for testing it, I'm going to merge it now because no further problems were found

**Pull request merged**
